languageCode = "en-us"
title = "Waking Life Movie Transcript"
baseurl = "https://wakinglifemovie.net/"
theme = "wakinglife"

[params]
  description = "Transcript for the wonderful movie Waking Life."
